// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
<<<<<<< HEAD
=======
<<<<<<< Updated upstream
=======
>>>>>>> feature/auto

    
    public static final class ControllerConstants{
        public static final int OPERATOR_PORT = 0;
    }

    public  static final class IntakeConstants {
        public static final int INTAKE_PORT = 6;
        public static final int ARM_PORT = 5;
        public static final int LIMIT_SWITCH = 4;
        public static final int GROUND_SWITCH = 3;
        
        public static final int LeftTalonSRX = 2;
        public static final int LeftVictorSPX = 1;
        public static final int RightTalonSRX = 4;
        public static final int RightVictorSPX = 3;
        
<<<<<<< HEAD
        public static final double FOLD_SPEED = -0.2;
        public static final double OPEN_SPEED = 0.2;
        public static final double INTAKE_SPEED = -0.5;
        public static final double OUTAKE_SPEED = 0.3;
    }
=======
        public static final double FOLD_SPEED = -0.15;
        public static final double OPEN_SPEED = 0.15;
        public static final double INTAKE_SPEED = -0.5;
        public static final double OUTAKE_SPEED = 0.3;
    }
>>>>>>> Stashed changes
>>>>>>> feature/auto
}

